metadata:
  name: "harnessgitopslab-deployment"
  spec:
    template:
      spec:
        containers:
          image: "luisredda/harness-java-demo-k8s:latests"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "harnessgitopslab"
    spec:
      containers:
      - image: "luisredda/harness-java-demo-k8s:latest"
        name: "harnessgitopslab"
  replicas: 1
  selector:
    matchLabels:
      app: "harnessgitopslab"
