createNamespace: true
serviceType: "LoadBalancer"
serviceTargetPort: 8888
image: "luisredda/harness-java-demo-k8s:latests"
replicas: 1
name: "harnessgitopslab"
namespace: "harnessgitopslab"
servicePort: 80
env:
  config:
    key1: "value1"
  secrets:
    key2: "value2"
